name: build-production

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: biocathub
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: biocathub/biocathub-frontend:latest
      - name: Create a repository dispatch event to trigger workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: deploy
          repo: StephanM87/BioCatHub_Linode
          token: ${{ secrets.WORKFLOW_PAT }}
          ref: master
          inputs: '{ "environment": "production" }'

